####滑膜成纤维细胞barcode提取
library(Seurat)
library(patchwork)
library(dplyr)
library(ggplot2)
setwd("/mnt/data7/yiyuan/Bone/test1/Fibroblasts/new/velocyto")
sce1 = readRDS("/mnt/data7/yiyuan/Bone/test1/Fibroblasts/new/sce_Fb_resubtype.final.rds")
head(sce1@meta.data)
barcodes <- Cells(sce1)
head(barcodes)