library(Seurat)
library(patchwork)
library(dplyr)
library(ggplot2)
setwd("/mnt/data7/yiyuan/Bone/test/Ch/Re_subtype/速率")
sce1 = readRDS("/mnt/data7/yiyuan/Bone/test/Ch/Re_subtype/sce_Ch_resubtype.final.rds")
head(sce1@meta.data)

barcodes <- Cells(sce1)
head(barcodes)
write.table(barcodes, file = "barcode.tsv", sep = "\t", quote = FALSE, col.names = FALSE, row.names = FALSE)
